version: "3"
services:
  httpd:
    # image: httpd:alpine
    build:
      dockerfile: Dockerfile
      context: .
    container_name: apache
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs
